-- AlterTable
ALTER TABLE `lostbag` ADD COLUMN `address` VARCHAR(191) NULL,
    ADD COLUMN `city` VARCHAR(191) NULL,
    ADD COLUMN `state` VARCHAR(191) NULL,
    ADD COLUMN `zipcode` VARCHAR(191) NULL;
